### ISSUE TITLE
Image & Font Bug

### ISSUE THREAD

**Issue by collectifbam** [arnaudjuracek/www-bam#11]
Sur Firefox + Chrome quand j'ajoute des images en liste en dessous d'un texte parfois il s'écrase
![screenshot-2018-1-9 collectif bam blockchain vaisselle](https://user-images.githubusercontent.com/35258160/34732966-1aa979f4-f567-11e7-8148-e271b1976c63.png)

**Comment by arnaudjuracek** [comment]
Est-ce que tu pourrais copier-coller le contenu markdown de l'article ? Je pense que ça a avoir avec un saut de ligne manquant :  

```md
Ceci est un paragraphe

- (image: )
- (image: )
```

**Comment by collectifbam** [comment]
Coucou ! Alors quand je mets du texte sous une image, avec une image + texte à côté, le texte s'écrase, voyez plutôt :

![capture d ecran 2018-01-23 a 18 58 29](https://user-images.githubusercontent.com/35258160/35292059-9e6e4f40-006f-11e8-90cd-75a0335ac8c2.png)

Merci
Bonne soirée !

**Comment by collectifbam** [comment]
Il y a la même chose quand on met le texte en haut...

Voilà le markdown qui va avec :

- (image: expo-presentation.jpg)Présentation de l'expérimentation et du « Retour des données personnelles[^Télécharger la (link: /content/5-projets/1-realisations/12-mesinfos/2-details/expo-presentation.jpg?1516648292 text:présentation de l'expériementation et du « Retour des données personnelles aux individus »).] ;
- (image: expo-experimentation.jpg)L'expérimentation en chiffres[^Télécharger la (link: /content/5-projets/1-realisations/12-mesinfos/2-details/expo-experimentation.jpg?1516648293 text:présentation de l'expériementation et du « Retour des données personnelles aux individus »).] ;

Et pour l'autre :

- Présentation de l'expérimentation et du « Retour des données personnelles (image: expo-presentation.jpg)[^Télécharger la (link: /content/5-projets/1-realisations/12-mesinfos/2-details/expo-presentation.jpg?1516648292 text:présentation de l'expériementation et du « Retour des données personnelles aux individus »).] ;
- L'expérimentation en chiffres (image: expo-experimentation.jpg)[^Télécharger la (link: /content/5-projets/1-realisations/12-mesinfos/2-details/expo-experimentation.jpg?1516648293 text:présentation de l'expériementation et du « Retour des données personnelles aux individus »).] ;

**Comment by arnaudjuracek** [comment]
Le problème vient du fait qu'en l'état tu ne peux pas mixer images et textes dans une même liste.
Dans le principe, une liste markdown sert à lister du texte. Pour des images, il suffit de les mettre les unes à la suite des autres pour avoir une séquence d'images.

Là où c'est peut-être un peu confusant, c'est que votre site est conçu pour interpreter des images mises en liste comme un mode "galerie" : en plus des listes de textes, tu peux donc faire des listes d'images pour les placer sur deux colonnes et rendre la mise en page plus intéressantes.

###### liste d'items textuels : ok
```md
- un item
- un autre item
```

###### galerie simple d'images : ok
```md
- (image: une_image.png)
- (image: une_autre_image.png)
```

###### mixer les deux : non
```md
- un texte
- (image: une_image.png)
- un texte et (image: une_image.png)
``` 

Comme tu mixes les deux modes dans une même liste, le site essaye d'interpreter le texte comme des blocs d'images et de les placer en colonnes, alors que ce n'est pas possible. 

Dans l'idée les articles n'étaient pas sensés comporter beaucoup d'images, mais principalement du texte. C'est pourquoi ce module de galerie était sensé suffire. Peut-être faudra-t-il concevoir, développer et éventuellement deviser un nouveau template pour des articles type "slideshow".

Une autre solution pourrait être de fournir des ressources téléchargeables pour les visiteurs souhaitant approfondir un projet, type pdf explicatif qui rentre dans le détail, avec une emphase sur les images plus que sur le texte cette fois.

Je peux également essayer de regarder pour pouvoir mixer textes et images, mais c'est très fortement probable qu'on se retrouve avec des cas particuliers très étranges (et compliqués à résoudre).

_Attention au passage, j'ai vu dans le fichier que tu utilisais la balise `<u></u>` mais le soulignement n'a pas été charté, tu as le soulignement navigateur par défaut._
