### ISSUE TITLE
Embed Kirby Video

### ISSUE THREAD

**Issue by collectifbam** [arnaudjuracek/www-bam#14]
C'est pas très grave j'utilise l'embed de youtube ou vimeo qui marche (sauf qu'il n'est pas tellement responsive) mais la syntaxe (vimeo: https://url/) ou (youtube: https://url/) ne fonctionne pas. Tu sais pourquoi ? (testé sur firefox et chrome )

![screenshot-2018-1-12 collectif bam bac a sable](https://user-images.githubusercontent.com/35258160/34890634-03a3e550-f7d3-11e7-9da0-ad7e9da0a83e.png)

**Comment by arnaudjuracek** [comment]
C'est corrigé, je te conseille d'utiliser la syntaxe kirby `(vimeo:)` `(youtube:)` pour avoir les embeds responsifs.
