### ISSUE TITLE
Crop Pictures

### ISSUE THREAD

**Issue by collectifbam** [arnaudjuracek/www-bam#15]
C'est un détail mais sur Firefox/windows au niveau des images il y a 1 ligne de pixels qui déborde du cadre blanc à chaque fois.

![screenshot-2018-1-13 collectif bam blockchain vaisselle](https://user-images.githubusercontent.com/35258160/34908042-95939a6c-f889-11e7-86ae-23230e057519.png)

**Comment by arnaudjuracek** [comment]
Tu peux me dire si le problème a été corrigé stp ? J'essaye un fix, mais je suis pas sûr que ça fonctionne sur windows.

**Comment by collectifbam** [comment]
ça marche ! (testé sur windows firefox et chrome)
