### ISSUE TITLE
Add FootNote Resume

### ISSUE THREAD

**Issue by collectifbam** [arnaudjuracek/www-bam#18]
Est-il possible de rajouter la fonction d'ajouter des notes de bas de page sur le texte de résumé ?

**Comment by arnaudjuracek** [comment]
Je le déconseille : le texte de résumé sert à décrire l'article et ne doit pas être trop chargé, car dans l'idée utilisé pour le SEO et les réseaux sociaux. C'est en soit une méta-donnée, ça serait bizarre de lui associer des méta-méta-données.

Si le texte de résumé doit contenir des notes de bas de page, peut-être qu'il faut le considérer comme une introduction plutôt que comme un chapeau d'article, et dans ce cas l'écrire dans le corps de l'article ?

**Comment by collectifbam** [comment]
Yes d'accord avec toi ! Du coup le texte résumé ne fait pas un peu répétition avec le résumé dans la sidebar ? Ok laissons pour le moment ce truc

**Comment by arnaudjuracek** [comment]
Non ce sont deux textes différents, le texte dans la sidebar est une courte phrase de description du projet, ou de la catégorie.
