### ISSUE TITLE
Meta-Données

### ISSUE THREAD

**Issue by collectifbam** [arnaudjuracek/www-bam#6]
Manque la fonction d'édition pour les méta-données en haut à droite des articles et des projets. D'ailleurs pour les projets il vaut mieux que la meta-donnée soit présente à droite dans la page résumé que dans la sidebar colorée
![screenshot-2018-1-9 collectif bam a propos](https://user-images.githubusercontent.com/35258160/34727060-131d9b2c-f556-11e7-912f-34b6ad664943.png)
.

**Comment by collectifbam** [comment]
Tu peux même enlever la possibilité des mettre des méta données à gauche dans la sidebar, ça prend trop de place.

**Comment by arnaudjuracek** [comment]
Tu peux me confirmer validation avec le reste de l'équipe stp ? 
C'était le comportement initial, qui a été changé suite à une réunion.

**Comment by collectifbam** [comment]
Yes je confirme :)
Désolé du changement, pour être sur tu parles du fait qu'il y ait les métadonnées à gauche ou qu'on ai enlevé la partie label à droite ?
En tout cas je ne trouve pas l'édition de cette partie dans le panel

**Comment by arnaudjuracek** [comment]
> Désolé du changement, pour être sur tu parles du fait qu'il y ait les métadonnées à gauche ou qu'on ai enlevé la partie label à droite ?

![image](https://user-images.githubusercontent.com/2837959/35198869-5dab96aa-fef5-11e7-922c-845337cd1ed6.png)
Je parle des méta-données des projets, que tu valides ne devant plus être dans la sidebar, mais comme sur les autres pages à droite de l'article.

Pour l'édition des méta-données d'articles, voir issue #19

**Comment by arnaudjuracek** [comment]
En fait c'est plus complexe que ça car il y a deux niveaux de métas-données : les méta-données d'un article (qui correspondent à ce que tu trouves à droite du texte), et les méta-données d'un projet, que tu trouves dans la sidebar.

Dans l'idée, en activant les méta-données d'article (voir #19), tu peux avoir **projets/`monprojet`/résumé** qui contient : 
- dans la sidebar, les méta-données de **`monprojet`**
- à droite, les méta-données de la page **résumé**.

En l'état, les méta-données d'article (#19) sont désactivées (la page `à propos` est un vestige, il n'y a pas de méta-données possibles normalement). Seules existent les méta-données de projet dans la sidebar donc.

Deux possibilités : 
- soit on active les méta-données pour un article (#19) et on peut donc avoir deux niveaux de méta-données (sidebar pour le projet + à droite pour l'article)
- soit on laisse désactivées les méta-données d'article, et on passe les méta-données de projets à droite. Ce qui veut dire que pour **projets/`monprojet`/résumé**, tu auras à droite les méta de **`monprojet`**, et sur la page **projets/`monprojet`/détails**, tu auras également ces méta-données. 

Je pencherais pour la deuxième solution, puisque en principe il n'y a pas à avoir de méta-données pour un article type `à propos` ou `histoire`. Les méta-données servent à donner des informations connexes (date, client, contexte) pour un projet.

**Comment by arnaudjuracek** [comment]
Je conseille donc de fermer #19 et de ne pas offrir la possibilité d'ajouter des méta-données à un article.

Les méta-données des articles d'un projet seront donc celles du projet, définies dans la page du projet et non dans les articles enfants.

**Comment by collectifbam** [comment]
Ok pour la deuxième solution (mais du coup de basculer l'affichage des méta données du projet dans la partie droite de l'article) pour éviter d'en avoir trop dans la sidebar, car dans l'idée on va avoir pas mal de metadonnées (date, licence, client, thème etc).
