### ISSUE TITLE
Disappearing Page - Sidebar

### ISSUE THREAD

**Issue by collectifbam** [arnaudjuracek/www-bam#9]
Quand je commence à remplir la page résumé d'un projet avec un peu de H2, la page Détails disparait dans le menu de la SideBar (même en scrollant).
Pb uniquement sur Firefox
ex : https://collectifbam.fr/v2/projets/realisations/blockchain-vaisselle/resume
![bug menu sidebar](https://user-images.githubusercontent.com/35258160/34730695-76ad3c10-f560-11e7-9473-543f7d4dc5ec.jpg)

**Comment by arnaudjuracek** [comment]
see #12
